<?xml version="1.0"?>
<package format="3">
  <name>uav_usv_bringup</name>
  <version>0.1.0</version>
  <description>Launch and parameter files for UAV-USV experiments.</description>
  <maintainer email="email@example.com">qin</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ros_gz_image</exec_depend>
  <exec_depend>uav_control</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
